import type { Document } from "@/shared/types";

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: "d-001",
    user_id: "u-001",
    filename: "Tăng huyết áp - Hướng dẫn điều trị 2024.pdf",
    file_size: 2_145_823,
    status: "done",
    entity_count: 87,
    relation_count: 142,
    created_at: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
    processed_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    id: "d-002",
    user_id: "u-001",
    filename: "Đái tháo đường type 2 - Case study.pdf",
    file_size: 856_211,
    status: "extracting",
    entity_count: 24,
    relation_count: 31,
    created_at: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
  },
  {
    id: "d-003",
    user_id: "u-001",
    filename: "Metformin - Pharmacokinetics review.pdf",
    file_size: 1_523_900,
    status: "verifying",
    entity_count: 52,
    relation_count: 78,
    created_at: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
  },
  {
    id: "d-004",
    user_id: "u-001",
    filename: "Suy tim sung huyết - Phác đồ Bach Mai.pdf",
    file_size: 3_412_700,
    status: "done",
    entity_count: 134,
    relation_count: 211,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    processed_at: new Date(Date.now() - 1000 * 60 * 60 * 3.8).toISOString(),
  },
  {
    id: "d-005",
    user_id: "u-001",
    filename: "COPD - Acute exacerbation management.pdf",
    file_size: 1_098_456,
    status: "failed",
    error_message: "Không thể đọc nội dung PDF — file có thể bị mã hóa.",
    entity_count: 0,
    relation_count: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "d-006",
    user_id: "u-001",
    filename: "Pneumonia - Clinical guidelines.pdf",
    file_size: 2_876_321,
    status: "done",
    entity_count: 96,
    relation_count: 158,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    processed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2 + 1000 * 60 * 5).toISOString(),
  },
];
